# Generated by Django 5.2.7 on 2025-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('uop', 'Umowa o pracę'), ('b2b', 'Kontrakt B2B'), ('zlecenie', 'Umowa zlecenie'), ('dzielo', 'Umowa o dzieło'), ('staz', 'Staź / Praktyka')], default='uop', max_length=50, verbose_name='Rodzaj umowy'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Obowiązki'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start pracy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='O sobie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/', verbose_name='Baner firmy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo firmy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Typ firmy (np. Software House)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='profile',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='Szczegółowy opis działalności'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, verbose_name='Wykształcenie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lata doświadczenia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data założenia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('N', 'Nie chcę podawać')], max_length=1, verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Narodowość'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numer telefonu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Zdjęcie profilowe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Krótki opis firmy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wielkość zespołu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Strona internetowa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_culture',
            field=models.TextField(blank=True, verbose_name='Opis pracy w firmie'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Opis stanowiska'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('none', 'Nie wymagane'), ('1-2', '1-2 lata'), ('3-5', '3-5 lat'), ('5+', '5+ lat')], default='none', max_length=20, verbose_name='Wymagane doświadczenie'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ważne do'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('stacjonarna', 'Stacjonarna'), ('hybrydowa', 'Hybrydowa'), ('zdalna', 'Zdalna')], default='stacjonarna', max_length=50, verbose_name='Tryb pracy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wynagrodzenie Max'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wynagrodzenie Min'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa firmy'),
        ),
    ]
