# Generated by Django 5.2.7 on 2026-01-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_job_contract_type_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stan cywilny'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('uop', 'Umowa o pracę'), ('b2b', 'Kontrakt B2B'), ('zlecenie', 'Umowa zlecenie'), ('dzielo', 'Umowa o dzieło'), ('staz', 'Staż / Praktyka')], default='uop', max_length=50, verbose_name='Rodzaj umowy'),
        ),
    ]
